[theme]
base = "dark"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#141414"
textColor = "#FFFFFF"
primaryColor = "#1DB954"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false